LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := AClient_share

LOCAL_MODULE_FILENAME := libAClient

LOCAL_SRC_FILES := \
AClient/main.cpp \
../../Classes/AppDelegate.cpp \
../../Classes/Common/CoCosAudioManager.cpp \
../../Classes/Common/DataPool.cpp \
../../Classes/Common/NameManager.cpp \
../../Classes/Common/SysTipMgr.cpp \
../../Classes/GameScene/BeginnerGuide.cpp \
../../Classes/GameScene/BeginnerGuideLayer.cpp \
../../Classes/GameScene/BeyondMap.cpp \
../../Classes/GameScene/Bullet.cpp \
../../Classes/GameScene/Chests.cpp \
../../Classes/GameScene/GameDataManager.cpp \
../../Classes/GameScene/GameEffectLayer.cpp \
../../Classes/GameScene/GameExpression.cpp \
../../Classes/GameScene/GameHelper.cpp \
../../Classes/GameScene/GameLayer.cpp \
../../Classes/GameScene/GameManager.cpp \
../../Classes/GameScene/GameMap.cpp \
../../Classes/GameScene/GameProcess.cpp \
../../Classes/GameScene/GameScene.cpp \
../../Classes/GameScene/GameTipsLayer.cpp \
../../Classes/GameScene/GameUILayer.cpp \
../../Classes/GameScene/GameVariable.cpp \
../../Classes/GameScene/GodDeviceManager.cpp \
../../Classes/GameScene/GridsManager.cpp \
../../Classes/GameScene/HallTechManager.cpp \
../../Classes/GameScene/Hero.cpp \
../../Classes/GameScene/IndicatorLayer.cpp \
../../Classes/GameScene/Item.cpp \
../../Classes/GameScene/ItemGrid.cpp \
../../Classes/GameScene/LoginScene.cpp \
../../Classes/GameScene/MapItem.cpp \
../../Classes/GameScene/MessageCenter.cpp \
../../Classes/GameScene/Monster.cpp \
../../Classes/GameScene/NPC.cpp \
../../Classes/GameScene/Pet.cpp \
../../Classes/GameScene/PetDataManager.cpp \
../../Classes/GameScene/PKMode.cpp \
../../Classes/GameScene/Player.cpp \
../../Classes/GameScene/Robot.cpp \
../../Classes/GameScene/RoleBuff.cpp \
../../Classes/GameScene/RoleFighter.cpp \
../../Classes/GameScene/RoleState_Dead.cpp \
../../Classes/GameScene/RoleState_Fight.cpp \
../../Classes/GameScene/RoleState_Forbiden.cpp \
../../Classes/GameScene/RoleState_Injured.cpp \
../../Classes/GameScene/RoleTitle.cpp \
../../Classes/GameScene/RoleTitleLayer.cpp \
../../Classes/GameScene/RootScene.cpp \
../../Classes/GameScene/Skill.cpp \
../../Classes/GameScene/SkillScript.cpp \
../../Classes/GameScene/SkillScriptFactory.cpp \
../../Classes/GameScene/TaskMgr.cpp \
../../Classes/GameScene/UpdateScene.cpp \
../../Classes/GameUpdate/GameUpdate.cpp \
../../Classes/GameUpdate/GameUpdateManager.cpp \
../../Classes/GameUpdate/GameUpdateUI.cpp \
../../Classes/HelloWorldScene.cpp \
../../Classes/Net/message.cpp \
../../Classes/Net/msg_achievement.cpp \
../../Classes/Net/msg_activeCenter.cpp \
../../Classes/Net/msg_battle.cpp \
../../Classes/Net/msg_betweenClientLs.cpp \
../../Classes/Net/msg_betweenLsGs.cpp \
../../Classes/Net/msg_betweenLsPs.cpp \
../../Classes/Net/msg_chat.cpp \
../../Classes/Net/msg_friend.cpp \
../../Classes/Net/msg_guild.cpp \
../../Classes/Net/msg_item.cpp \
../../Classes/Net/msg_mail.cpp \
../../Classes/Net/msg_mall.cpp \
../../Classes/Net/msg_map.cpp \
../../Classes/Net/msg_move.cpp \
../../Classes/Net/msg_nonInGame.cpp \
../../Classes/Net/msg_others.cpp \
../../Classes/Net/msg_pet.cpp \
../../Classes/Net/msg_role.cpp \
../../Classes/Net/msg_sale.cpp \
../../Classes/Net/msg_task.cpp \
../../Classes/Net/msg_team.cpp \
../../Classes/Net/msg_trade.cpp \
../../Classes/Net/NetDispatcher.cpp \
../../Classes/Net/NetDispatcherHandle_Achievement.cpp \
../../Classes/Net/NetDispatcherHandle_ActivityCenter.cpp \
../../Classes/Net/NetDispatcherHandle_Battle.cpp \
../../Classes/Net/NetDispatcherHandle_betweenLsPs.cpp \
../../Classes/Net/NetDispatcherHandle_Chat.cpp \
../../Classes/Net/NetDispatcherHandle_friend.cpp \
../../Classes/Net/NetDispatcherHandle_Guid.cpp \
../../Classes/Net/NetDispatcherHandle_item.cpp \
../../Classes/Net/NetDispatcherHandle_Login.cpp \
../../Classes/Net/NetDispatcherHandle_LS2C.cpp \
../../Classes/Net/NetDispatcherHandle_mail.cpp \
../../Classes/Net/NetDispatcherHandle_Mall.cpp \
../../Classes/Net/NetDispatcherHandle_Map.cpp \
../../Classes/Net/NetDispatcherHandle_Mine.cpp \
../../Classes/Net/NetDispatcherHandle_Others.cpp \
../../Classes/Net/NetDispatcherHandle_Pet.cpp \
../../Classes/Net/NetDispatcherHandle_Role.cpp \
../../Classes/Net/NetDispatcherHandle_Sale.cpp \
../../Classes/Net/NetDispatcherHandle_Task.cpp \
../../Classes/Net/NetDispatcherHandle_Team.cpp \
../../Classes/Net/NetDispatcherHandle_Trade.cpp \
../../Classes/Net/pk_achievement.cpp \
../../Classes/Net/pk_activeCenter.cpp \
../../Classes/Net/pk_battle.cpp \
../../Classes/Net/pk_betweenClientLs.cpp \
../../Classes/Net/pk_betweenLsGs.cpp \
../../Classes/Net/pk_betweenLsPs.cpp \
../../Classes/Net/pk_chat.cpp \
../../Classes/Net/pk_friend.cpp \
../../Classes/Net/pk_guild.cpp \
../../Classes/Net/pk_item.cpp \
../../Classes/Net/pk_mail.cpp \
../../Classes/Net/pk_mall.cpp \
../../Classes/Net/pk_map.cpp \
../../Classes/Net/pk_move.cpp \
../../Classes/Net/pk_nonInGame.cpp \
../../Classes/Net/pk_others.cpp \
../../Classes/Net/pk_pet.cpp \
../../Classes/Net/pk_role.cpp \
../../Classes/Net/pk_sale.cpp \
../../Classes/Net/pk_task.cpp \
../../Classes/Net/pk_team.cpp \
../../Classes/Net/pk_trade.cpp \
../../Classes/UI/AddLegionUI.cpp \
../../Classes/UI/ChatMainUI.cpp \
../../Classes/UI/CommonUI.cpp \
../../Classes/UI/CopyEnd.cpp \
../../Classes/UI/CopyMapUI.cpp \
../../Classes/UI/CreatePlayer.cpp \
../../Classes/UI/CustomCtrl/CdCtrol.cpp \
../../Classes/UI/CustomCtrl/ComboBox.cpp \
../../Classes/UI/CustomCtrl/DragCtrol.cpp \
../../Classes/UI/CustomCtrl/GridArrayUI.cpp \
../../Classes/UI/CustomCtrl/GridIcon.cpp \
../../Classes/UI/CustomCtrl/JoyStick.cpp \
../../Classes/UI/CustomCtrl/MenuForPlayer.cpp \
../../Classes/UI/CustomCtrl/NumberAdjuster.cpp \
../../Classes/UI/CustomCtrl/PageNum.cpp \
../../Classes/UI/CustomCtrl/ProgressBar.cpp \
../../Classes/UI/CustomCtrl/RadioButtonSet.cpp \
../../Classes/UI/CustomCtrl/RichTextEX.cpp \
../../Classes/UI/CustomCtrl/ScrollBar.cpp \
../../Classes/UI/CustomCtrl/ScrollGrids.cpp \
../../Classes/UI/CustomCtrl/ScrollList.cpp \
../../Classes/UI/CustomCtrl/ScrollMenu.cpp \
../../Classes/UI/CustomCtrl/ScrollMsgWindow.cpp \
../../Classes/UI/CustomCtrl/ScrollTable.cpp \
../../Classes/UI/CustomCtrl/TimerProgressBar.cpp \
../../Classes/UI/CustomCtrl/TuoYuanAction.cpp \
../../Classes/UI/CustomCtrl/UnderLinedText.cpp \
../../Classes/UI/DramaUI.cpp \
../../Classes/UI/FightPause.cpp \
../../Classes/UI/FreeFightScoreUI.cpp \
../../Classes/UI/FriendUI.cpp \
../../Classes/UI/GamePrompt.cpp \
../../Classes/UI/GameUI.cpp \
../../Classes/UI/GameUIWithOutSideTouchEvent.cpp \
../../Classes/UI/GodDeviceUI.cpp \
../../Classes/UI/HallTechUI.cpp \
../../Classes/UI/HeroInfo.cpp \
../../Classes/UI/ItemTipsUI.cpp \
../../Classes/UI/LegionUI.cpp \
../../Classes/UI/LoadingUI.cpp \
../../Classes/UI/LoginUI.cpp \
../../Classes/UI/MailUI.cpp \
../../Classes/UI/MainUIFight.cpp \
../../Classes/UI/MainUINormal.cpp \
../../Classes/UI/ManufactureUI.cpp \
../../Classes/UI/MessageBoxUI.cpp \
../../Classes/UI/MissionUI.cpp \
../../Classes/UI/NpcDialog.cpp \
../../Classes/UI/OneStroke.cpp \
../../Classes/UI/OpenLock.cpp \
../../Classes/UI/Relive.cpp \
../../Classes/UI/ResMgr/CtrlAllocator.cpp \
../../Classes/UI/ReviveUI.cpp \
../../Classes/UI/RoleAttriUI.cpp \
../../Classes/UI/RolePackageUI.cpp \
../../Classes/UI/RoleSelectUI.cpp \
../../Classes/UI/SelectPlayer.cpp \
../../Classes/UI/ServerList.cpp \
../../Classes/UI/SkyBookUI.cpp \
../../Classes/UI/StrengthenUI.cpp \
../../Classes/UI/TaskDialog.cpp \
../../Classes/UI/TaskUI.cpp \
../../Classes/UI/TeamApplicationUI.cpp \
../../Classes/UI/TeamUI.cpp \
../../Classes/UI/UIWorldMap.cpp \
../../Classes/UI/WaitMessageUI.cpp \
../../Classes/UI/WaveEnd.cpp \
../../Classes/UIData/CCopyDataMgr.cpp \
../../Classes/UIData/CMatchMachine.cpp \
../../Classes/UIData/Legion.cpp \

LOCAL_C_INCLUDES := $(LOCAL_PATH) \
					$(LOCAL_PATH)/../../Classes \
					$(LOCAL_PATH)/../../Classes/Common \
					$(LOCAL_PATH)/../../cocos2d/cocos/2d \
					$(LOCAL_PATH)/../../cocos2d/cocos/editor-support \
					$(LOCAL_PATH)/../../cocos2d/cocos/ui \
					$(LOCAL_PATH)/../../cocos2d/cocos/2d/render \
					$(LOCAL_PATH)/../../cocos2d/cocos/base \
					$(LOCAL_PATH)/../../cocos2d/cocos/physics \
					$(LOCAL_PATH)/../../cocos2d/cocos/math/kazmath \
					$(LOCAL_PATH)/../../cocos2d/extensions \
					$(LOCAL_PATH)/../../cocos2d/external \
					$(LOCAL_PATH)/../../cocos2d/cocos/2d/platform/android \
					$(LOCAL_PATH)/../../google-breakpad/src \
					$(LOCAL_PATH)/../../librpg \
					$(LOCAL_PATH)/../../librpg/map \
					$(LOCAL_PATH)/../../librpg/role \
					$(LOCAL_PATH)/../../librpg/audio \
					$(LOCAL_PATH)/../../libzm \
					$(LOCAL_PATH)/../../libzm/mpq \
					$(LOCAL_PATH)/../../libzm/socket \
					$(LOCAL_PATH)/../../third-libs/include \
					$(LOCAL_PATH)/../../third-libs/include/libmpg123

LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_extension_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocostudio_static
LOCAL_WHOLE_STATIC_LIBRARIES += zm_static
LOCAL_WHOLE_STATIC_LIBRARIES += rpg_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_curl_static
LOCAL_WHOLE_STATIC_LIBRARIES += breakpad_client

include $(BUILD_SHARED_LIBRARY)

$(call import-module,2d)
$(call import-module,extensions)
$(call import-module,audio/android)
$(call import-module,editor-support/cocostudio)
$(call import-module,librpg)
$(call import-module,libzm)
$(call import-module,curl/prebuilt/android)
$(call import-module,android/google_breakpad)
